repos:
  # Python Backend
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.7
    hooks:
      - id: ruff
        args: [--fix]
        files: ^backend/
      - id: ruff-format
        files: ^backend/

  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        files: ^backend/

  # TypeScript Frontend
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.54.0
    hooks:
      - id: eslint
        files: ^frontend/src/.*\.(ts|tsx)$
        additional_dependencies:
          - eslint@8.54.0
          - "@typescript-eslint/parser@6.12.0"
          - "@typescript-eslint/eslint-plugin@6.12.0"
          - eslint-config-prettier@9.0.0
          - eslint-plugin-prettier@5.0.1
          - prettier@3.1.0
        args: [--fix]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: ^frontend/src/.*\.(ts|tsx|js|jsx|json|css|md)$

  # General
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ["--maxkb=5000"]  # Allow up to 5MB for images
        exclude: ^frontend/node_modules/
      - id: check-case-conflict
      - id: detect-private-key
      - id: mixed-line-ending

  # Security - prevent committing sensitive data
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package-lock.json

  # Python type checking (optional - can be slow)
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.7.1
  #   hooks:
  #     - id: mypy
  #       files: ^backend/src/
  #       args: [--ignore-missing-imports]

  # Fast unit tests before commit (optional)
  # - repo: local
  #   hooks:
  #     - id: pytest-fast
  #       name: Run fast unit tests
  #       entry: bash -c 'cd backend && uv run pytest tests/unit/ -x -q'
  #       language: system
  #       pass_filenames: false
  #       always_run: false
  #       stages: [commit]
