version: "3.8"

services:
  redis:
    image: redis/redis-stack:7.4.0-v1
    container_name: redis-wellness
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis-data:/data
    environment:
      - REDIS_ARGS=--save 60 1000
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - wellness-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: redis-wellness-backend
    ports:
      - "8000:8000"
    volumes:
      # Mount health data for auto-import on startup
      - ./apple_health_export:/apple_health_export:ro
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - REDIS_SESSION_TTL_SECONDS=18144000
      - REDIS_HEALTH_DATA_TTL_SECONDS=18144000
      - REDIS_DEFAULT_TTL_DAYS=210
      - USER_HEALTH_CONTEXT=${USER_HEALTH_CONTEXT}
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - wellness-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: redis-wellness-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - wellness-network

networks:
  wellness-network:
    driver: bridge

volumes:
  redis-data:
